# Generated by Django 4.2.1 on 2023-05-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
